src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * This class is part of the skeleton project provided for students of the
 * course "Softwaredevelopment and Project Management" offered by the University
 * of Innsbruck.
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUser(currentUserName);
        }
        return currentUser;
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return name;
    }

    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

    public boolean isParent() {
        return hasRole(UserRole.PARENT.toString());
    }

    public boolean isInactiveParent() {
        return hasRole(UserRole.INACTPARENT.toString());
    }

    public boolean isStaff() {
        return hasRole(UserRole.STAFF.toString());
    }
}

src/main/webapp/WEB-INF/includes/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
        <ui:composition>

            <div style="float: right;">
                <ui:fragment rendered="#{sessionInfoBean.loggedIn}">
                    Angemeldet als #{sessionInfoBean.currentUserName}
                </ui:fragment>
                <ui:fragment rendered="#{!sessionInfoBean.loggedIn}">
                    Nicht angemeldet
                </ui:fragment>
            </div>

        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/includes/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <body>

        <ui:composition>

            <h:form>
                <p:panel style="margin-bottom: 10px">
                    <div style="margin-bottom: 150px">
                        <div style="float: left">
                            <center><h1>#{configurationService.config.name}</h1></center>
                        </div>
                        <img style="height:150px; float:right" src="#{configurationService.config.logoUrl}" />
                    </div>
                </p:panel>

                <!-- menu for staff -->
                <p:menubar rendered="#{sessionInfoBean.staff}">
                    <p:menuitem url="/secured/welcome.xhtml" icon="ui-icon-home" title="Icon Only"/>
                    <p:submenu label="Planer">
                        <p:menuitem value="Kalender" url="/staff/planner_table.xhtml"/>
                        <p:menuitem value="Tagesliste" url="/staff/planner_list.xhtml"/>
                    </p:submenu>
                    <p:submenu label="Kinder">
                        <p:menuitem value="Übersicht" url="/staff/child_overview.xhtml"/>
                        <p:menuitem value="Bezugspersonen" url="/staff/child_referenceperson.xhtml" />
                        <p:menuitem value="Tagesausnahmen" url="/staff/manage_requests.xhtml" />
                        <p:menuitem value="Kontaktliste" url="/staff/child_contacts.xhtml" />
                    </p:submenu>
                    <p:submenu label="Benutzer">
                        <p:menuitem value="Erziehungsberechtigte" url="/staff/manage_parents.xhtml"/>
                        <p:menuitem value="Personal" url="/staff/manage_staff.xhtml" />
                    </p:submenu>
                    <p:menuitem value="Aufgaben" url="/staff/task_manage.xhtml"/>
                    <p:submenu label="System">
                        <p:menuitem value="Konfiguration" url="/staff/manage_config.xhtml" />
                        <p:menuitem value="Feiertage" url="/staff/manage_holidays.xhtml" />
                    </p:submenu>
                    <p:menuitem value="Login" url="/login.xhtml" rendered="#{!sessionInfoBean.loggedIn}"/>
                    <p:menuitem value="Logout" url="/logout" rendered="#{sessionInfoBean.loggedIn}"/>
                </p:menubar>

                <!-- menu for parents -->
                <p:menubar rendered="#{sessionInfoBean.parent}">
                    <p:menuitem url="/secured/welcome.xhtml" icon="ui-icon-home" title="Icon Only"/>
                    <p:menuitem value="Meine Aufgaben" url="/parents/tasks.xhtml" />
                    <p:menuitem value="Meine Kinder" url="/parents/child_data.xhtml" />
                    <p:menuitem value="Bezugspersonen" url="/parents/child_referenceperson.xhtml" />
                    <p:menuitem value="Anfragen" url="/parents/manage_requests.xhtml" />
                    <p:menuitem value="Meine Daten" url="/parents/manage_mydata.xhtml"/>    
                    <p:menuitem value="Login" url="/login.xhtml" rendered="#{!sessionInfoBean.loggedIn}"/>
                    <p:menuitem value="Logout" url="/logout" rendered="#{sessionInfoBean.loggedIn}"/>
                </p:menubar>
            </h:form>
        </ui:composition>
    </body>
</html>